# Generated by Django 4.2.29 on 2026-03-16 11:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('context', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('question_type', models.CharField(choices=[('SUBJECTIVE_SLIDER', 'Subjective Slider (0-100)'), ('PREDICTIVE_BINARY', 'Binary Prediction (0-100% Probability)'), ('PREDICTIVE_CHOICE', 'Categorical Prediction (Probability Distribution)')], default='SUBJECTIVE_SLIDER', max_length=30)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Required for PREDICTIVE_CHOICE', size=None)),
                ('resolution_state', models.CharField(choices=[('N_A', 'Not Applicable (Subjective)'), ('PENDING', 'Pending Resolution'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled / Invalid')], default='N_A', max_length=20)),
                ('resolution_date', models.DateTimeField(blank=True, help_text='When the prediction objectively resolves.', null=True)),
                ('resolved_truth', models.JSONField(blank=True, help_text='Stores the factual outcome once resolved.', null=True)),
                ('requires_web_search', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed (Voting Only, No AI)'), ('ACTIVE', 'Active (Has AI Data)'), ('ARCHIVED', 'Archived (Locked)')], db_index=True, default='PROPOSED')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_auto_poll', models.BooleanField(db_index=True, default=False)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_questions', to=settings.AUTH_USER_MODEL)),
                ('latest_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_for_question', to='ai_engine.consensusrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumanVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('complex_forecast', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_votes', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnonymousVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('complex_forecast', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_votes', to='questions.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='humanvote',
            constraint=models.CheckConstraint(check=models.Q(('score__isnull', True), models.Q(('score__gte', 0.0), ('score__lte', 100.0)), _connector='OR'), name='questions_humanvote_valid_score'),
        ),
        migrations.AlterUniqueTogether(
            name='humanvote',
            unique_together={('question', 'user')},
        ),
        migrations.AddConstraint(
            model_name='anonymousvote',
            constraint=models.CheckConstraint(check=models.Q(('score__isnull', True), models.Q(('score__gte', 0.0), ('score__lte', 100.0)), _connector='OR'), name='questions_anonymousvote_valid_score'),
        ),
        migrations.AddConstraint(
            model_name='anonymousvote',
            constraint=models.UniqueConstraint(fields=('question', 'session_key'), name='unique_anonymous_vote'),
        ),
    ]
