# Generated by Django 4.2.29 on 2026-03-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_skip_vote',
            field=models.BooleanField(default=False, help_text='If true, users can see results without voting.'),
        ),
    ]
