# Generated by Django 4.2.29 on 2026-03-16 22:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_allow_skip_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Required for PREDICTIVE_CHOICE. Use 'Other' as the final element for auto-balancing.", size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='resolved_truth',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
