# Generated by Django 4.2.29 on 2026-03-17 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_choices_alter_question_resolved_truth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousvote',
            name='reasoning',
            field=models.TextField(blank=True, help_text='Optional justification for the vote.'),
        ),
        migrations.AddField(
            model_name='humanvote',
            name='reasoning',
            field=models.TextField(blank=True, help_text='Optional justification for the vote.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Default options for the question.', size=None),
        ),
    ]
