# Generated by Django 4.2.29 on 2026-03-18 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_engine', '0002_initial'),
        ('questions', '0004_anonymousvote_reasoning_humanvote_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='admin_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='target_models',
            field=models.ManyToManyField(blank=True, help_text='Specific AI models to run this against. Leave blank for system defaults.', to='ai_engine.aimodel'),
        ),
        migrations.AddField(
            model_name='question',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review (Admin Approval Pending)'), ('REJECTED', 'Rejected (Needs Edits)'), ('PROPOSED', 'Proposed (Voting & Upvoting, No AI)'), ('ACTIVE', 'Active (Has AI Data)'), ('ARCHIVED', 'Archived (Locked)')], db_index=True, default='IN_REVIEW'),
        ),
    ]
