# Generated by Django 4.2.29 on 2026-03-19 13:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_remove_airesponse_selected_choice_and_more'),
        ('questions', '0005_question_admin_feedback_question_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_priority',
            field=models.IntegerField(db_index=True, default=0, help_text='Higher numbers are processed first.'),
        ),
        migrations.AddField(
            model_name='question',
            name='orchestration_queued',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, the orchestrator will process this next.'),
        ),
        migrations.AlterField(
            model_name='anonymousvote',
            name='reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='humanvote',
            name='reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='allow_skip_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.TextField(help_text='Provide background info to help voters and AI models understand the scope.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='target_models',
            field=models.ManyToManyField(blank=True, to='ai_engine.aimodel'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='The core question or prediction.', max_length=255),
        ),
    ]
