# Generated by Django 4.2.29 on 2026-03-19 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_ai_priority_question_orchestration_queued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model_group_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text="Automatically query all active models with these tags (e.g., 'free', 'frontier').", size=None),
        ),
    ]
