# Generated by Django 4.2.29 on 2026-03-16 11:02

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('api_identifier', models.CharField(max_length=100, unique=True)),
                ('developer', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('normalized_score', models.FloatField(blank=True, null=True)),
                ('selected_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('complex_forecast', models.JSONField(blank=True, null=True)),
                ('summary_sentence', models.TextField()),
                ('is_refusal', models.BooleanField(default=False)),
                ('refusal_reason', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConsensusRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synthesis_summary', models.TextField(blank=True)),
                ('minority_report', models.TextField(blank=True)),
                ('polarization_index', models.FloatField(default=0.0)),
                ('verified_sentiment_avg', models.FloatField(blank=True, null=True)),
                ('public_sentiment_avg', models.FloatField(blank=True, null=True)),
                ('aggregated_forecast', models.JSONField(blank=True, null=True)),
                ('prompt_version', models.CharField(blank=True, default='v1.0', max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
