# Generated by Django 4.2.29 on 2026-03-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consensusrun',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='questions.question'),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.aimodel'),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ai_engine.consensusrun'),
        ),
        migrations.AddConstraint(
            model_name='airesponse',
            constraint=models.CheckConstraint(check=models.Q(('normalized_score__isnull', True), models.Q(('normalized_score__gte', 0.0), ('normalized_score__lte', 100.0)), _connector='OR'), name='ai_engine_airesponse_valid_ai_score'),
        ),
    ]
