# Generated by Django 4.2.29 on 2026-03-19 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='consensusrun',
            name='aggregated_forecast',
        ),
        migrations.RemoveField(
            model_name='consensusrun',
            name='public_sentiment_avg',
        ),
        migrations.RemoveField(
            model_name='consensusrun',
            name='verified_sentiment_avg',
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='cost',
            field=models.DecimalField(decimal_places=10, default=Decimal('0E-10'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='consensusrun',
            name='total_cost',
            field=models.DecimalField(decimal_places=10, default=Decimal('0E-10'), max_digits=15),
        ),
    ]
