# Generated by Django 4.2.29 on 2026-03-19 14:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_remove_airesponse_selected_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILURE', 'Failure')], max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('log_message', models.TextField()),
                ('total_run_cost', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=15)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='aimodel',
            options={'verbose_name': 'AI Model'},
        ),
        migrations.AlterModelOptions(
            name='airesponse',
            options={'verbose_name': 'AI Response'},
        ),
        migrations.RemoveConstraint(
            model_name='airesponse',
            name='ai_engine_airesponse_valid_ai_score',
        ),
        migrations.RemoveField(
            model_name='airesponse',
            name='raw_json',
        ),
        migrations.AlterField(
            model_name='consensusrun',
            name='prompt_version',
            field=models.CharField(blank=True, default='v1.2', max_length=50),
        ),
    ]
