# Generated by Django 4.2.29 on 2026-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_orchestrationlog_alter_aimodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponse',
            name='complex_forecast',
            field=models.JSONField(blank=True, help_text='REQUIRED FOR CHOICE TYPE. Format: [{"choice": "Brazil", "confidence": 40.0}, {"choice": "France", "confidence": 60.0}]', null=True),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='normalized_score',
            field=models.FloatField(blank=True, help_text='For Slider/Binary: 0-100 score.', null=True),
        ),
    ]
