# Generated by Django 4.2.29 on 2026-03-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_alter_airesponse_complex_forecast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='is_manual_entry',
            field=models.BooleanField(default=False, help_text='Checked if this was added manually via admin.'),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='complex_forecast',
            field=models.JSONField(blank=True, help_text='REQUIRED FOR CHOICE TYPE. Format: [{"choice": "Brazil", "confidence": 40.0}]', null=True),
        ),
    ]
