# Generated by Django 4.2.29 on 2026-03-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_airesponse_is_manual_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consensusrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='complex_forecast',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='is_manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='normalized_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
